### ISSUE TITLE
Geri Bildirim

### ISSUE THREAD

**Issue by ramazansancar** [mesutpol/programlama_algoritma_giris#221]
Sorular ve içerikler MD ile daha okunaklı ve güzel bir görünüme kavuşturulabilir.

**Comment by mesutpol** [comment]
Bu repo ders kapsamında öğrencilerin hazırladığı örneklerdir. MD ile daha okunaklı yapılması konusunda öğrencileride bilgilendireceğim. Geri bildiriminiz için teşekkür ederiz.

**Comment by ramazansancar** [comment]
Rica ederim. Kolay gelsin. Destek olabileceğim bir konu varsa yazabilirsiniz :)
